DROP TABLE IF EXISTS global_health_nutrition;

CREATE TABLE global_health_nutrition (
    "Country" REAL,
    "Year" REAL,
    "Gender" REAL,
    "Life Expectancy" REAL,
    "Infant Mortality Rate" REAL,
    "Low CI Value Infant Mortality Rate" REAL,
    "High CI Value Infant Mortality Rate" REAL,
    "Under 5 Mortality Rate" REAL,
    "Low CI Value Under 5 Mortality Rate" REAL,
    "High CI Value Under 5 Mortality Rate" REAL,
    "% Death Cardiovascular" REAL,
    "Low CI Value % Death Cardiovascular" REAL,
    "High CI Value % Death Cardiovascular" REAL,
    "Suicides Rate" REAL,
    "Alcohol Abuse" REAL,
    "Air Pollution Death Rate Stroke" REAL,
    "Low CI Value Air Pollution Death Rate Stroke" REAL,
    "High CI Value Air Pollution Death Rate Stroke" REAL,
    "Air Pollution Death Rate Stroke Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Stroke Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Stroke Age Standarized" REAL,
    "Air Pollution Death Rate Ischaemic Heart Disease" REAL,
    "Low CI Value Air Pollution Death Rate Ischaemic Heart Disease" REAL,
    "High CI Value Air Pollution Death Rate Ischaemic Heart Disease" REAL,
    "Air Pollution Death Rate Ischaemic Heart Disease Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Ischaemic Heart Disease Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Ischaemic Heart Disease Age Standarized" REAL,
    "Air Pollution Death Rate Lower Respiratory Infections" REAL,
    "Low CI Value Air Pollution Death Rate Lower Respiratory Infections" REAL,
    "High CI Value Air Pollution Death Rate Lower Respiratory Infections" REAL,
    "Air Pollution Death Rate Lower Respiratory Infections Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Lower Respiratory Infections Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Lower Respiratory Infections Age Standarized" REAL,
    "Air Pollution Death Rate Chronic Obstructive Pulmonary Disease" REAL,
    "Low CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease" REAL,
    "High CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease" REAL,
    "Air Pollution Death Rate Chronic Obstructive Pulmonary Disease Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease Age Standarized" REAL,
    "Air Pollution Death Rate Total" REAL,
    "Low CI Value Air Pollution Death Rate Total" REAL,
    "High CI Value Air Pollution Death Rate Total" REAL,
    "Air Pollution Death Rate Total Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Total Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Total Age Standarized" REAL,
    "Air Pollution Death Rate Trachea Bronchus Lung Cancers" REAL,
    "Low CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers" REAL,
    "High CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers" REAL,
    "Air Pollution Death Rate Trachea Bronchus Lung Cancers Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers Age Standarized" REAL,
    "Unsafe Wash Mortality Rate" REAL,
    "Poisoning Mortality Rate" REAL,
    "Tobacco Prevalence" REAL,
    "% Population Aged 0-14" REAL,
    "% Population Aged 15-64" REAL,
    "% Population Aged 65+" REAL,
    "% Population Aged 65-69" REAL,
    "% Population Aged 70-74" REAL,
    "% Population Aged 75-79" REAL,
    "% Population Aged 80+" REAL,
    "Maternal Mortality Ratio" REAL,
    "Low CI Value Maternal Mortality Ratio" REAL,
    "High CI Value Maternal Mortality Ratio" REAL,
    "% of Births Attended By Skilled Personal" REAL,
    "Neonatal Mortality Rate" REAL,
    "Low CI Value Neonatal Mortality Rate" REAL,
    "High CI Value Neonatal Mortality Rate" REAL,
    "Incidence of Malaria" REAL,
    "Incidence of Tuberculosis" REAL,
    "Low CI Value Incidence of Tuberculosis" REAL,
    "High CI Value Incidence of Tuberculosis" REAL,
    "Hepatitis B Surface Antigen" REAL,
    "Low CI Value Hepatitis B Surface Antigen" REAL,
    "High CI Value Hepatitis B Surface Antigen" REAL,
    "Intervention Against NTDs" REAL,
    "Road Traffic Deaths" REAL,
    "Reproductive Age Women" REAL,
    "Adolescent Birth Rate" REAL,
    "Universal Heath Care Coverage" REAL,
    "Population 10 Percentage SDG Total" REAL,
    "Population 10 Percentage SDG Urban" REAL,
    "Population 10 Percentage SDG Rural" REAL,
    "Population 25 Percentage SDG Total" REAL,
    "Population 25 Percentage SDG Urban" REAL,
    "Population 25 Percentage SDG Rural" REAL,
    "Doctors" REAL,
    "Nurses and Midwifes" REAL,
    "Dentists" REAL,
    "Pharmacists" REAL,
    "Basic Drinking Water Services" REAL,
    "Basic Sanization Services Total" REAL,
    "Basic Sanization Services Urban" REAL,
    "Basic Sanization Services Rural" REAL,
    "Safely Sanitation Total" REAL,
    "Safely Sanitation Urban" REAL,
    "Safely Sanitation Rural" REAL,
    "Basic Hand Washing Total" REAL,
    "Basic Hand Washing Urban" REAL,
    "Basic Hand Washing Rural" REAL,
    "Clean Fuel and Technology" REAL,
    "Birth Rate" REAL,
    "Battle Related Deaths" REAL,
    "% Injury Deaths" REAL,
    "Death Rate" REAL,
    "GDP per Capita" REAL,
    "% Population $1.90 a day" REAL,
    "% Population $3.20 a day" REAL,
    "% Population $5.50 a day" REAL,
    "Income per Capita" REAL,
    "Total Population" REAL,
    "GNI per Capita" REAL,
    "Conflict and Terrorism Deaths" REAL,
    "Homicide Rate" REAL,
    "Government Expenditure Education" REAL,
    "Government Expenditure Military" REAL,
    "Government Expenditure Health" REAL,
    "Diet Composition Alcoholic Beverages" REAL,
    "Diet Composition Other" REAL,
    "Diet Composition Sugar" REAL,
    "Diet Composition Oils And Fats" REAL,
    "Diet Composition Meat" REAL,
    "Diet Composition Dairy And Eggs" REAL,
    "Diet Composition Fruit And Vegetables" REAL,
    "Diet Composition Starchy Roots" REAL,
    "Diet Composition Pulses" REAL,
    "Diet Composition Cereals And Grains" REAL,
    "Vegetable Consumption" REAL,
    "Fruit Consumption Plantains" REAL,
    "Fruit Consumption Other" REAL,
    "Fruit Consumption Bananas" REAL,
    "Fruit Consumption Dates" REAL,
    "Fruit Consumption Other Citrus" REAL,
    "Fruit Consumption Oranges And Mandarines" REAL,
    "Fruit Consumption Apples" REAL,
    "Fruit Consumption Lemons And Limes" REAL,
    "Fruit Consumption Grapes" REAL,
    "Fruit Consumption Grapefruit" REAL,
    "Fruit Consumption Pineapples" REAL,
    "Cereal Consumption Oats" REAL,
    "Cereal Consumption Rye" REAL,
    "Cereal Consumption Barley" REAL,
    "Cereal Consumption Sorghum" REAL,
    "Cereal Consumption Maize" REAL,
    "Cereal Consumption Wheat" REAL,
    "Cereal Consumption Rice" REAL,
    "Diet Calories Animal Protein" REAL,
    "Diet Calories Plant Protein" REAL,
    "Diet Calories Fat" REAL,
    "Diet Calories Carbohydrates" REAL
);