
---

## 3. SQL scripts

Assume you use SQLite with a DB file at `data/db/global_health_nutrition.db`.

### `sql/01_create_table.sql`

Uses actual column names from the CSV. Types are mostly `REAL` for simplicity.

```sql
DROP TABLE IF EXISTS global_health_nutrition;

CREATE TABLE global_health_nutrition (
    Country TEXT,
    Year INTEGER,
    Gender TEXT,
    "Life Expectancy" REAL,
    "Infant Mortality Rate" REAL,
    "Low CI Value Infant Mortality Rate" REAL,
    "High CI Value Infant Mortality Rate" REAL,
    "Under 5 Mortality Rate" REAL,
    "Low CI Value Under 5 Mortality Rate" REAL,
    "High CI Value Under 5 Mortality Rate" REAL,
    "% Death Cardiovascular" REAL,
    "Low CI Value % Death Cardiovascular" REAL,
    "High CI Value % Death Cardiovascular" REAL,
    "Suicides Rate" REAL,
    "Alcohol Abuse" REAL,
    "Air Pollution Death Rate Stroke" REAL,
    "Low CI Value Air Pollution Death Rate Stroke" REAL,
    "High CI Value Air Pollution Death Rate Stroke" REAL,
    "Air Pollution Death Rate Stroke Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Stroke Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Stroke Age Standarized" REAL,
    "Air Pollution Death Rate Ischaemic Heart Disease" REAL,
    "Low CI Value Air Pollution Death Rate Ischaemic Heart Disease" REAL,
    "High CI Value Air Pollution Death Rate Ischaemic Heart Disease" REAL,
    "Air Pollution Death Rate Ischaemic Heart Disease Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Ischaemic Heart Disease Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Ischaemic Heart Disease Age Standarized" REAL,
    "Air Pollution Death Rate Lower Respiratory Infections" REAL,
    "Low CI Value Air Pollution Death Rate Lower Respiratory Infections" REAL,
    "High CI Value Air Pollution Death Rate Lower Respiratory Infections" REAL,
    "Air Pollution Death Rate Lower Respiratory Infections Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Lower Respiratory Infections Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Lower Respiratory Infections Age Standarized" REAL,
    "Air Pollution Death Rate Chronic Obstructive Pulmonary Disease" REAL,
    "Low CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease" REAL,
    "High CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease" REAL,
    "Air Pollution Death Rate Chronic Obstructive Pulmonary Disease Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease Age Standarized" REAL,
    "Air Pollution Death Rate Total" REAL,
    "Low CI Value Air Pollution Death Rate Total" REAL,
    "High CI Value Air Pollution Death Rate Total" REAL,
    "Air Pollution Death Rate Total Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Total Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Total Age Standarized" REAL,
    "Air Pollution Death Rate Trachea Bronchus Lung Cancers" REAL,
    "Low CI Value AIr Pollution Death Rate Trachea Bronchus Lung Cancers" REAL,
    "High CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers" REAL,
    "Air Pollution Death Rate Trachea Bronchus Lung Cancers Age Standarized" REAL,
    "Low CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers Age Standarized" REAL,
    "High CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers Age Standarized" REAL,
    "Hepatitis B Surface Antigen" REAL,
    "Low CI Value Hepatitis B Surface Antigen" REAL,
    "High CI Value Hepatitis B Surface Antigen" REAL,
    "Intervention Against NTDs" REAL,
    "Road Traffic Deaths" REAL,
    "Reproductive Age Women" REAL,
    "Adolescent Birth Rate" REAL,
    "Universal Heath Care Coverage" REAL,
    "Population 10 Percentage SDG Total" REAL,
    "Population 10 Percentage SDG Urban" REAL,
    "Population 10 Percentage SDG Rural" REAL,
    "Population 25 Percentage SDG Total" REAL,
    "Population 25 Percentage SDG Urban" REAL,
    "Population 25 Percentage SDG Rural" REAL,
    "Doctors" REAL,
    "Nurses and Midwifes" REAL,
    "Dentists" REAL,
    "Pharmacists" REAL,
    "Basic Drinking Water Services" REAL,
    "Basic Sanization Services Total" REAL,
    "Basic Sanization Services Urban" REAL,
    "Basic Sanization Services Rural" REAL,
    "Safely Sanitation Total" REAL,
    "Safely Sanitation Urban" REAL,
    "Safely Sanitation Rural" REAL,
    "Basic Hand Washing Total" REAL,
    "Basic Hand Washing Urban" REAL,
    "Basic Hand Washing Rural" REAL,
    "Clean Fuel and Technology" REAL,
    "Birth Rate" REAL,
    "Battle Related Deaths" REAL,
    "% Injury Deaths" REAL,
    "Death Rate" REAL,
    "GDP per Capita" REAL,
    "Diabetes Prevelance" REAL,
    "Musculoskeletal Disorder Prevelance" REAL,
    "Severe Mental Disorder Prevelance" REAL,
    "Obesity Prevelance" REAL,
    "Overweight Prevelance" REAL,
    "Raised Blood Pressure Prevelance" REAL,
    "Raised Total Cholesterol Prevelance" REAL,
    "Cancer Prevelance" REAL,
    "Rural Population Percentage" REAL,
    "Urban Population Percentage" REAL,
    "Alcohol Deaths Population" REAL,
    "Total Deaths" REAL,
    "Alcohol Deaths" REAL,
    "Fruit Consumption Bananas" REAL,
    "Fruit Consumption Oranges and Mandarins" REAL,
    "Fruit Consumption Apples" REAL,
    "Fruit Consumption Lemons And Limes" REAL,
    "Fruit Consumption Grapes" REAL,
    "Fruit Consumption Grapefruit" REAL,
    "Fruit Consumption Pineapples" REAL,
    "Cereal Consumption Oats" REAL,
    "Cereal Consumption Rye" REAL,
    "Cereal Consumption Barley" REAL,
    "Cereal Consumption Sorghum" REAL,
    "Cereal Consumption Maize" REAL,
    "Cereal Consumption Wheat" REAL,
    "Cereal Consumption Rice" REAL,
    "Diet Calories Animal Protein" REAL,
    "Diet Calories Plant Protein" REAL,
    "Diet Calories Fat" REAL,
    "Diet Calories Carbohydrates" REAL
);
